<letra> ::= [a-zA-Z_]
<letras> ::= <letra>+
<digito> ::= [0-9]
<digito_no_cero> ::=[1-9]
<espacio> ::= " "
<espacios> ::= <espacio>+
<salto_linea> ::= "\n"
<simbolos> ::= "!" | '"' | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "]" | "^" | "_" | "`" | "{" | "|" | "}" | "~" | "¿" 

<parentesis_apertura> ::= "<|"
<parentesis_cierre> ::= "|>"
<operador> ::= "+" | "-" | "*" | "/" | "%" | "^" 
<asignacion> ::= "<-"
<separador> ::= "~"
<coma> ::= ","
<final_expresion> ::= "!"
<incremento> ::= "++"
<decremento> ::= "--"
<negativo> ::= "-"
<delimitador_bloque_inicio> ::= "|:"
<delimitador_bloque_fin> ::= ":|"
<delimitador_indice_inicio> ::= "<<"
<delimitador_indice_fin> ::= ">>"
<inicio_comentario> ::= "¡¡"
<inicio_comentario_bloque> ::= "{-"
<fin_comentario_bloque> ::= "-}"
<conjuncion_logica> ::= "@"
<disyuncion_logica> ::= "#"
<negacion_logica> ::= "$"
<less_t> ::= "less_t"
<less_te> ::= "less_te"
<greather_t> ::= "greather_t"
<greather_te> ::= "greather_te"
<equal> ::= "equal"
<n_equal> ::= "n_equal"

<tipos_de_datos> ::= "char" | "float" | "string" | "bool" | "int"
<tipos_de_datos_arreglo> ::= "float" | "int"
<tipos_de_datos_funcion> ::= "char" | "float" | "bool" | "int" | "string" 
<tipo_de_dato_programa> ::= "empty"

<valores_booleanos> ::= "true" | "false"
<cadena> ::= '"' (<letras> | <espacio> | <digito> | <simbolos>)* '"'
<caracter> ::= "'" (<letra> | <digito> | <simbolos>) "'"

<entero_positivo> ::= "0" | <digito_no_cero> <digito>*
<entero_negativo> ::= "-" <digito_no_cero> <digito>*
<enteros> ::= <entero_positivo> | <entero_negativo>
<entero_exponencial> ::= <entero_positivo> "e" <entero_positivo>
<decimal> ::= "." <digito>+
<numero> ::= <enteros> <decimal>? | "-" "0" <decimal> | <entero_exponencial>
<numero_fraccionario> ::= (<enteros> "/" <enteros> | <enteros> "//" <enteros>)
<numeros> ::= <numero> | <numero_fraccionario>

<numero_positivo> ::= <entero_positivo> <decimal>? | <entero_exponencial>
<numero_fraccionario_positivo> ::= (<entero_positivo> "/" <entero_positivo> | <entero_positivo> "//" <entero_positivo>)
<numeros_positivos> ::= <numero_positivo> | <numero_fraccionario_positivo>

<literal> ::= <numeros_positivos> | <cadena> | <caracter> | <valores_booleanos>
<identificador> ::= <letras> (<letras> | <digito>)*

<comentario> ::= <comentario_una_linea> | <comentario_bloque>
<comentario_una_linea> ::= <inicio_comentario> (<numeros> | <letras> | <espacio> | <simbolos>)*
<comentario_bloque> ::= <inicio_comentario_bloque> (<numeros> | <letras> | <espacio> | <salto_linea> | <simbolos>)* <fin_comentario_bloque>

<expresion_primaria> ::= <literal> | <identificador> | <acceso_arreglo> | <llamada_funcion> | <parentesis_apertura> <expresion> <parentesis_cierre>

<expresion_unaria_base> ::= <negacion_logica>+ <expresion_primaria> | <expresion_primaria>
<expresion_unaria_menos> ::= <negativo> <espacio>* <expresion_unaria_base> | <negativo> <espacios> <expresion_unaria_menos> | <negativo> <espacio>* <expresion_unaria_mas> | <decremento> <identificador>
<expresion_unaria_mas> ::= <incremento> <identificador>

<expresion_potencia_base> ::= <expresion_unaria_base> ("^" <expresion_potencia>)?
<expresion_potencia_menos> ::= <expresion_unaria_menos> ("^" <expresion_potencia>)?
<expresion_potencia_mas> ::= <expresion_unaria_mas> ("^" <expresion_potencia>)?
<expresion_potencia> ::= <expresion_potencia_base> | <expresion_potencia_menos> | <expresion_potencia_mas>

<expresion_multiplicacion_base> ::= <expresion_potencia_base> (("*" | "/" | "%") <espacio>* <expresion_potencia>)*
<expresion_multiplicacion_menos> ::= <expresion_potencia_menos> (("*" | "/" | "%") <espacio>* <expresion_potencia>)*
<expresion_multiplicacion_mas> ::= <expresion_potencia_mas> (("*" | "/" | "%") <espacio>* <expresion_potencia>)*
<expresion_multiplicacion> ::= <expresion_multiplicacion_base> | <expresion_multiplicacion_menos> | <expresion_multiplicacion_mas>

<suma_operacion> ::= "+" <espacio>* <expresion_multiplicacion_base> | "+" <espacios> <expresion_multiplicacion_mas> | "+" <espacio>* <expresion_multiplicacion_menos>
<resta_operacion> ::= "-" <espacio>* <expresion_multiplicacion_base> | "-" <espacios> <expresion_multiplicacion_mas> | "-" <espacios> <expresion_multiplicacion_menos>

<expresion_suma> ::= <expresion_multiplicacion> (<suma_operacion> | <resta_operacion>)*

<relacional_numerico_funcional> ::= (<less_t> | <less_te> | <greather_t> | <greather_te>) <parentesis_apertura> <expresion_suma> <coma> <expresion_suma> <parentesis_cierre>
<expresion_relacional_numerica> ::= <expresion_suma> | <relacional_numerico_funcional>
<igualdad_funcional> ::= (<equal> | <n_equal>) <parentesis_apertura> <expresion> <coma> <expresion> <parentesis_cierre>
<expresion_igualdad> ::= <expresion_relacional_numerica> | <igualdad_funcional>
<expresion_conjuncion> ::= <expresion_igualdad> (<conjuncion_logica> <expresion_igualdad>)*
<expresion_disyuncion> ::= <expresion_conjuncion> (<disyuncion_logica> <expresion_conjuncion>)*
<expresion> ::= <expresion_disyuncion>

<sentencia_expresion> ::= <expresion> <final_expresion>

<acceso_arreglo> ::= <identificador> <delimitador_indice_inicio> <expresion> <delimitador_indice_fin> <delimitador_indice_inicio> <expresion> <delimitador_indice_fin>

<asignacion_variable> ::= <asignacion> <expresion>
<crear_variable> ::= <tipos_de_datos> <separador> <identificador> <asignacion_variable>? <final_expresion>
<asignar_variable> ::= <identificador> <asignacion> <expresion> <final_expresion>
<dimension> ::= <entero_positivo>

<fila_de_arreglos> ::= <delimitador_bloque_inicio> <numero> (<coma> <numero>)* <delimitador_bloque_fin>
<elementos_arreglos> ::= <delimitador_bloque_inicio> <fila_de_arreglos> (<coma> <fila_de_arreglos>)* <delimitador_bloque_fin>
<asignacion_arreglo_bidimensional> ::= <asignacion> <elementos_arreglos>
<crear_arreglo_bidimensional> ::= <tipos_de_datos_arreglo> <separador> <identificador> <delimitador_indice_inicio> <dimension> <delimitador_indice_fin> <delimitador_indice_inicio> <dimension> <delimitador_indice_fin> <asignacion_arreglo_bidimensional>? <final_expresion>
<modificar_elemento_arreglo> ::= <acceso_arreglo> <asignacion> <expresion> <final_expresion>

<parametro> ::= <tipos_de_datos> <separador> <identificador>

<cin> ::= "cin" <parentesis_apertura> <identificador> <parentesis_cierre> <final_expresion>
<cout> ::= "cout" <parentesis_apertura> (<numero> | <cadena> | <caracter> | <valores_booleanos> | <identificador>) <parentesis_cierre> <final_expresion>

<lista_sentencias> ::= <sentencia>+
<sentencia> ::= <crear_variable> | <asignar_variable> | <crear_arreglo_bidimensional> | <modificar_elemento_arreglo> | <sentencia_if> | <sentencia_do_while> | <sentencia_switch> | <sentencia_return> | <sentencia_break> | <cin> | <cout> | <llamada_funcion> <final_expresion> | <sentencia_expresion>
<condicion_booleana> ::= <expresion>

<sentencia_if> ::= "if" <parentesis_apertura> <condicion_booleana> <parentesis_cierre> <delimitador_bloque_inicio> <lista_sentencias>? <delimitador_bloque_fin> ("else" <delimitador_bloque_inicio> <lista_sentencias>? <delimitador_bloque_fin>)?
<sentencia_do_while> ::= "do" <delimitador_bloque_inicio> <lista_sentencias>? <delimitador_bloque_fin> "while" <parentesis_apertura> <condicion_booleana> <parentesis_cierre> <final_expresion>

<sentencia_return> ::= "return" <separador> <expresion> <final_expresion>
<sentencia_break> ::= "break" <final_expresion>

<literal_caso> ::= <numero> | <caracter>
<caso_switch> ::= "case" <separador> <literal_caso> ":" <lista_sentencias>? <sentencia_break>?
<sentencia_switch> ::= "switch" <parentesis_apertura> <expresion> <parentesis_cierre> <delimitador_bloque_inicio> <caso_switch>+ ("default" ":" <lista_sentencias>?)? <delimitador_bloque_fin>

<llamada_funcion> ::= <identificador> <parentesis_apertura> (<expresion> (<coma> <expresion>)*)? <parentesis_cierre>
<crear_funcion> ::= <tipos_de_datos_funcion> <separador> <identificador> <parentesis_apertura> (<parametro> (<coma> <parametro>)*)? <parentesis_cierre> <delimitador_bloque_inicio> <lista_sentencias>? <delimitador_bloque_fin>

<programa> ::= (<crear_funcion>)* <main>
<main> ::= <tipo_de_dato_programa> <separador> "__main__" <parentesis_apertura> <parentesis_cierre> <delimitador_bloque_inicio> <lista_sentencias>? <delimitador_bloque_fin>