
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESS_TE = 23;
  public static final int POW = 35;
  public static final int STRING_LITERAL = 52;
  public static final int INCREMENT = 28;
  public static final int MULT = 32;
  public static final int CHAR = 4;
  public static final int CHAR_LITERAL = 53;
  public static final int EMPTY = 7;
  public static final int BLOCK_END = 41;
  public static final int CASE = 15;
  public static final int INT = 2;
  public static final int MINUS = 31;
  public static final int DECREMENT = 29;
  public static final int INDEX_START = 44;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int BLOCK_START = 40;
  public static final int OR = 37;
  public static final int COMMA = 47;
  public static final int BOOL = 6;
  public static final int SEPARATOR = 46;
  public static final int DIV = 33;
  public static final int PLUS = 30;
  public static final int ASSIGN = 39;
  public static final int MAIN = 21;
  public static final int IF = 10;
  public static final int ID = 50;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 26;
  public static final int STRING_TYPE = 5;
  public static final int GREATHER_TE = 25;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int MOD = 34;
  public static final int CIN = 19;
  public static final int BREAK = 17;
  public static final int NUM_LITERAL = 51;
  public static final int SWITCH = 14;
  public static final int COLON = 49;
  public static final int ELSE = 11;
  public static final int INDEX_END = 45;
  public static final int COUT = 20;
  public static final int N_EQUAL = 27;
  public static final int WHILE = 13;
  public static final int DEFAULT = 16;
  public static final int FLOAT = 3;
  public static final int GREATHER_T = 24;
  public static final int END_EXPR = 48;
  public static final int PAREN_CLOSE = 43;
  public static final int FALSE = 9;
  public static final int LESS_T = 22;
  public static final int DO = 12;
  public static final int PAREN_OPEN = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING_TYPE",
  "BOOL",
  "EMPTY",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "CIN",
  "COUT",
  "MAIN",
  "LESS_T",
  "LESS_TE",
  "GREATHER_T",
  "GREATHER_TE",
  "EQUAL",
  "N_EQUAL",
  "INCREMENT",
  "DECREMENT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "POW",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "BLOCK_START",
  "BLOCK_END",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "INDEX_START",
  "INDEX_END",
  "SEPARATOR",
  "COMMA",
  "END_EXPR",
  "COLON",
  "ID",
  "NUM_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL"
  };
}

